var config = {
	"sites": { // Order matters
		// EN
		"www.kaspersky.com.au":		{ "domain": "comau",	"tags": ["en", "full"],	"alias": ["au", "australia", "comau", "e-au"] },
		"www.kaspersky.com":			{ "domain": "com",		"tags": ["en", "full"],	"alias": ["com", "e-global", "e-com", "global"] },
		"www.kaspersky.co.in":		{ "domain": "coin",		"tags": ["en", "full"],	"alias": ["coin", "e-in", "in", "india"] },
		"me-en.kaspersky.com":		{ "domain": "me-en",	"tags": ["en", "full"],	"alias": ["e-me-en", "me-en", "meen", "middle east en"] },
		"www.kaspersky.co.za":		{ "domain": "coza",		"tags": ["en", "full"],	"alias": ["coza", "e-za", "south africa", "za"] },
		"www.kaspersky.co.uk":		{ "domain": "couk",		"tags": ["en", "full"],	"alias": ["couk", "e-uk", "gb", "uk"] },
		"usa.kaspersky.com":			{ "domain": "usa",		"tags": ["en", "full"],	"alias": ["e-usa", "us", "usa"] },
		// FULL Non EN
		"www.kaspersky.be":				{ "domain": "be",			"tags": ["nonen", "full"],	"alias": ["be", "belgium", "f-be"] },
		"www.kaspersky.com.br":		{ "domain": "combr",	"tags": ["nonen", "full"],	"alias": ["br", "brazil", "combr", "f-br"] },
		"www.kaspersky.com.cn":		{ "domain": "comcn",	"tags": ["nonen", "full"],	"alias": ["china", "cn", "comcn", "f-cn"] },
		"www.kaspersky.de":				{ "domain": "de",			"tags": ["nonen", "full"],	"alias": ["de", "f-de", "germany"] },
		"www.kaspersky.dk":				{ "domain": "dk",			"tags": ["nonen", "full"],	"alias": ["denmark", "dk", "f-dk"] },
		"www.kaspersky.es":				{ "domain": "es",			"tags": ["nonen", "full"],	"alias": ["es", "f-es", "spain"] },
		"www.kaspersky.fi":				{ "domain": "fi",			"tags": ["nonen", "full"],	"alias": ["f-fi", "fi", "finland"] },
		"www.kaspersky.fr":				{ "domain": "fr",			"tags": ["nonen", "full"],	"alias": ["f-fr", "fr", "france"] },
		"www.kaspersky.it":				{ "domain": "it",			"tags": ["nonen", "full"],	"alias": ["f-it", "it", "italy"] },
		"www.kaspersky.co.jp":		{ "domain": "cojp",		"tags": ["nonen", "full"],	"alias": ["cojp", "f-jp", "japan", "jp"] },
		"latam.kaspersky.com":		{ "domain": "latam",	"tags": ["nonen", "full"],	"alias": ["f-latam", "latam"] },
		"me.kaspersky.com":				{ "domain": "me",			"tags": ["nonen", "full"],	"alias": ["ae", "f-me-ar", "me", "me-ar", "meae", "mear", "middle east ar"] },
		"www.kaspersky.nl":				{ "domain": "nl",			"tags": ["nonen", "full"],	"alias": ["f-nl", "netherlands", "nl"] },
		"no.kaspersky.com":				{ "domain": "no",			"tags": ["nonen", "full"],	"alias": ["f-no", "no", "norway"] },
		"www.kaspersky.ru":				{ "domain": "ru",			"tags": ["nonen", "full"],	"alias": ["f-ru", "ru", "russia"] },
		"www.kaspersky.se":				{ "domain": "se",			"tags": ["nonen", "full"],	"alias": ["f-se", "se", "sv", "sweeden"] },
		"www.kaspersky.com.tr":		{ "domain": "comtr",	"tags": ["nonen", "full"],	"alias": ["comtr", "f-tr", "tr", "turkey"] },
		// LITE sites
		"afrique.kaspersky.com":	{ "domain": "afrique",	"tags": ["nonen", "lite"],	"alias": ["afrique", "french africa", "l-afrique"] },
		"bg.kaspersky.com":				{ "domain": "bg",				"tags": ["nonen", "lite"],	"alias": ["bg", "bulgaria", "l-bg"] },
		"www.kaspersky.ca":				{ "domain": "ca",				"tags": ["en", "lite"],			"alias": ["ca", "ca-en", "caen", "canada", "canada en", "l-ca-en"] },
		"www.kaspersky.ca/fr":		{ "domain": "cafr",			"tags": ["nonen", "lite"],	"alias": ["ca-fr", "cafr", "canada fr", "l-ca-fr"] },
		"www.kaspersky.cz":				{ "domain": "cz",				"tags": ["nonen", "lite"],	"alias": ["cz", "czech", "l-cz"] },
		"www.kaspersky.gr":				{ "domain": "gr",				"tags": ["nonen", "lite"],	"alias": ["gr", "greece", "l-gr"] },
		"hu.kaspersky.com":				{ "domain": "hu",				"tags": ["nonen", "lite"],	"alias": ["hu", "hungary", "l-hu"] },
		"www.kaspersky.com.hk":		{ "domain": "comhk",		"tags": ["nonen", "lite"],	"alias": ["comhk", "hk", "hong kong", "hong kong zh", "hong-kong", "l-hk"] },
		"id.kaspersky.com":				{ "domain": "id",				"tags": ["nonen", "lite"],	"alias": ["id", "l-id", "indonesia"] },
		"www.kaspersky.kz":				{ "domain": "kz",				"tags": ["nonen", "lite"],	"alias": ["kz", "kzkz", "kz-kz", "l-kz", "l-kz-kz", "kazakhstan"] },
		"www.kaspersky.kz/ru":		{ "domain": "kzru",			"tags": ["nonen", "lite"],	"alias": ["kzru", "kz-ru", "l-kz-ru", "l-kzru", "kazakhstan-ru"] },
		"www.kaspersky.co.kr":		{ "domain": "cokr",			"tags": ["nonen", "lite"],	"alias": ["cokr", "korea", "kr", "l-kr"] },
		"www.kaspersky.ma":				{ "domain": "ma",				"tags": ["nonen", "lite"],	"alias": ["l-ma", "ma", "maroc", "marocco"] },
		"www.kaspersky.pt":				{ "domain": "pt",				"tags": ["nonen", "lite"],	"alias": ["l-pt", "portugal", "pt"] },
		"www.kaspersky.ro":				{ "domain": "ro",				"tags": ["nonen", "lite"],	"alias": ["l-ro", "ro", "romania"] },
		"www.kaspersky.rs":				{ "domain": "rs",				"tags": ["nonen", "lite"],	"alias": ["l-rs", "rs", "serbia", "sr"] },
		"www.kaspersky.co.th":		{ "domain": "coth",			"tags": ["nonen", "lite"],	"alias": ["coth", "l-th", "th", "thailand"] },
		"www.kaspersky.com.tw":		{ "domain": "comtw",		"tags": ["nonen", "lite"],	"alias": ["comtw", "l-tw", "taiwan", "tw"] },
		"www.kaspersky.com.vn":		{ "domain": "comvn",		"tags": ["nonen", "lite"],	"alias": ["comvn", "l-vn", "vietnam", "vn"] }
	},
	"domains": {
		"afrique": "afrique.kaspersky.com",
		"be": "www.kaspersky.be",
		"bg": "bg.kaspersky.com",
		"ca": "www.kaspersky.ca",
		"cafr": "www.kaspersky.ca/fr",
		"coin": "www.kaspersky.co.in",
		"cojp": "www.kaspersky.co.jp",
		"cokr": "www.kaspersky.co.kr",
		"com": "www.kaspersky.com",
		"comau": "www.kaspersky.com.au",
		"combr": "www.kaspersky.com.br",
		"comcn": "www.kaspersky.com.cn",
		"comhk": "www.kaspersky.com.hk",
		"comtr": "www.kaspersky.com.tr",
		"comtw": "www.kaspersky.com.tw",
		"comvn": "www.kaspersky.com.vn",
		"coth": "www.kaspersky.co.th",
		"couk": "www.kaspersky.co.uk",
		"coza": "www.kaspersky.co.za",
		"cz": "www.kaspersky.cz",
		"de": "www.kaspersky.de",
		"dk": "www.kaspersky.dk",
		"es": "www.kaspersky.es",
		"fi": "www.kaspersky.fi",
		"fr": "www.kaspersky.fr",
		"gr": "www.kaspersky.gr",
		"hu": "hu.kaspersky.com",
		"id": "id.kaspersky.com",
		"it": "www.kaspersky.it",
		"latam": "latam.kaspersky.com",
		"ma": "www.kaspersky.ma",
		"me": "me.kaspersky.com",
		"me-en": "me-en.kaspersky.com",
		"nl": "www.kaspersky.nl",
		"no": "no.kaspersky.com",
		"pt": "www.kaspersky.pt",
		"ro": "www.kaspersky.ro",
		"rs": "www.kaspersky.rs",
		"ru": "www.kaspersky.ru",
		"se": "www.kaspersky.se",
		"usa": "usa.kaspersky.com",
		"kz": "www.kaspersky.kz",
		"kzru": "www.kaspersky.kz/ru"
	},
	"pages": {
		"b2c": "/home-security",
		"vsb": "/small-business-security",
		"smb": "/small-to-medium-business-security",
		"ent": "/enterprise-security",
		"abt": "/about",
		"standard": "/standard",
		"plus": "/plus",
		"premium": "/premium",
		"kav": "/antivirus",
		"kis": "/internet-security",
		"kts": "/total-security",
		"ksc": "/security-cloud",
		"ksk": "/safe-kids",
		"ksec": "/vpn-secure-connection",
		"kpm": "/password-manager",
		"free": "/free-antivirus"
	},
	"verdicts": {
		"b2b_channel_fallback":	"business",
		"b2c_early_renewal_fallback":	"home",
		"free":	"free-standard",
		"free_plus":	"free-plus",
		"free_plus_trial":	"free-plus",
		"free_premium":	"free-premium",
		"free_standard_trial":	"free-standard",
		"kav":	"kav",
		"kav_b":	"kav",
		"kav_retail":	"kav",
		"kav_retail_2":	"kav",
		"kav_standard":	"kav-standard",
		"kav_standard_1y":	"kav-standard",
		"kav_standard_acq":	"kav-standard",
		"kav_standard_retail":	"kav-standard",
		"kav_t":	"kav",
		"kesb_t":	"kesb-trial",
		"kesb_t_advanced":	"kesb-trial",
		"kesbadvanced_b":	"kesbadvanced",
		"kesbadvanced_b2b_channel_fallback":	"kesbadvanced",
		"kesbadvanced_b_nfr":	"kesbadvanced",
		"kesbadvanced_early_reneval_fallback":	"kesbadvanced",
		"kesbadvanced_late_90":	"kesbadvanced",
		"kesbcloud":	"kesbcloud",
		"kesbcloud_b":	"kesbcloud",
		"kesbcloud_b2b_channel_fallback":	"kesbselect",
		"kesbcloud_b_nfr":	"kesbcloud",
		"kesbcloud_late_365":	"kesbcloud",
		"kesbcloud_late_90":	"kesbcloud",
		"kesbcloudbase":	"kesbcloudbase",
		"kesbcloudbase_b":	"kesbcloudbase",
		"kesbcloudbase_late_365":	"kesbcloudbase",
		"kesbcloudbase_late_90":	"kesbcloudbase",
		"kesbcloudplus":	"kesbcloudplus",
		"kesbcloudplus_b":	"kesbcloudplus",
		"kesbcloudplus_b2b_channel_fallback":	"kesbcloudplus",
		"kesbcloudplus_late_365":	"kesbcloudplus",
		"kesbcloudplus_late_90":	"kesbcloudplus",
		"kesbcloudplus_t_nfr":	"kesbcloudpro-trial",
		"kesbcloudplus_t_plus_nfr":	"kesbcloudpro-trial",
		"kesbcloudpro":	"kesbcloudpro",
		"kesbcloudpro_b":	"kesbcloudpro",
		"kesbcloudpro_t":	"kesbcloudpro-trial",
		"kesbselect_b":	"kesbselect",
		"kesbselect_b2b_channel_fallback":	"kesbselect-cloudplus",
		"kesbselect_b_nfr":	"kesbselect",
		"kesbselect_early_renewal_fallback":	"kesbselect",
		"kesbselect_late_365":	"kesbselect",
		"kesbselect_late_90":	"kesbselect",
		"kesdcloud_b2b_channel_fallback":	"kesbcloud",
		"kfa":	"free-standard",
		"kis":	"kis",
		"kis_ex":	"kis",
		"kis_plus":	"kis-plus",
		"kis_plus_1d_exp":	"kis-plus",
		"kis_plus_1y":	"kis-plus",
		"kis_plus_acq":	"kis-plus",
		"kis_plus_retail":	"kis-plus",
		"kis_retail":	"kis",
		"kis_retail_2":	"kis",
		"kis_t":	"kis",
		"kisa_plus":	"kisa-plus",
		"kisa_plus_acq":	"kisa-plus",
		"kisandroid":	"kisandroid",
		"kisandroid_b":	"kisandroid",
		"kisandroid_retail":	"kisandroid",
		"kisandroid_t":	"kisandroid",
		"kismac":	"kismac",
		"kismac_b":	"kismac",
		"kismac_plus":	"kismac-plus",
		"kismac_plus_1y":	"kismac-plus",
		"kismac_plus_acq":	"kismac-plus",
		"kismac_retail":	"kismac",
		"kismac_t":	"kismac",
		"kpm":	"kpm",
		"kpm_b":	"kpm",
		"kpm_t":	"kpm",
		"ksc_fam":	"ksc-per",
		"ksc_fam_20":	"ksc-fam",
		"ksc_fam_premium":	"ksc-premium",
		"ksc_fam_premium_1y":	"ksc-premium",
		"ksc_fam_premium_acq":	"ksc-premium",
		"ksc_fam_t":	"ksc-fam",
		"ksc_fam_t_nfr":	"ksc-fam",
		"ksc_free_fam":	"free-standard",
		"ksc_free_per":	"free-standard",
		"ksc_per":	"ksc-per",
		"ksc_per_premium":	"ksc-premium",
		"ksc_per_premium_1y":	"ksc-premium",
		"ksc_per_premium_acq":	"ksc-premium",
		"ksc_per_t":	"ksc-per",
		"ksec":	"ksec",
		"ksec_b":	"ksec",
		"ksec_t":	"ksec",
		"ksk":	"ksk",
		"ksk_b":	"ksk",
		"ksk_t":	"ksk",
		"ksos":	"ksos",
		"ksos_5wofs":	"ksos",
		"ksos_b":	"ksos",
		"ksos_b_nfr":	"ksos",
		"ksos_retail":	"ksos",
		"ksos_t":	"ksos",
		"kts":	"kts",
		"kts_b":	"kts",
		"kts_premium":	"kts-premium",
		"kts_premium_1y":	"kts-premium",
		"kts_premium_acq":	"kts-premium",
		"kts_premium_retail":	"kts-premium",
		"kts_retail":	"kts",
		"kts_retail_2":	"kts",
		"kts_t":	"kts",
		"plus":	"plus",
		"plus_after_fl":	"home",
		"plus_b":	"plus",
		"plus_no_vpn":	"home",
		"plus_no_vpn_b":	"home",
		"plus_no_vpn_t":	"home",
		"plus_t":	"plus",
		"plus_too":	"plus",
		"premium":	"premium",
		"premium_after_fl":	"home",
		"premium_b":	"premium-trial",
		"premium_no_vpn":	"home",
		"premium_no_vpn_b":	"home",
		"premium_no_vpn_t":	"home",
		"premium_t":	"premium-trial",
		"standard":	"standard",
		"standard_after_fl":	"home",
		"standard_b":	"standard",
		"standard_t":	"standard"
	},
	"geoIP": [
		"AD","AE","AF","AG","AI","AL","AM","AO","AP","AQ","AR","AS","AT","AU","AW","AX","AZ",
		"BA","BB","BD","BE","BF","BG","BH","BI","BJ","BL","BM","BN","BO","BQ","BR","BS","BT","BV","BW","BY","BZ",
		"CA","CC","CD","CF","CG","CH","CI","CK","CL","CM","CN","CO","CR","CU","CV","CW","CX","CY","CZ","DE","DJ",
		"DK","DM","DO","DZ",
		"EC","EE","EG","EH","ER","ES","ET","EU",
		"FI","FJ","FK","FM","FO","FR",
		"GA","GB","GD","GE","GF","GG","GH","GI","GL","GM","GN","GP","GQ","GR","GS","GT","GU","GW","GY",
		"HK","HM","HN","HR","HT","HU",
		"ID","IE","IL","IM","IN","IO","IQ","IR","IS","IT",
		"JE","JM","JO","JP",
		"KE","KG","KH","KI","KM","KN","KP","KR","KW","KY","KZ",
		"LA","LB","LC","LI","LK","LR","LS","LT","LU","LV","LY",
		"MA","MC","MD","ME","MF","MG","MH","MK","ML","MM","MN","MO","MP","MQ","MR","MS","MT","MU","MV","MW","MX","MY","MZ",
		"NA","NC","NE","NF","NG","NI","NL","NO","NP","NR","NU","NZ",
		"OM",
		"PA","PE","PF","PG","PH","PK","PL","PM","PN","PR","PS","PT","PW","PY",
		"QA",
		"RE","RO","RS","RU","RW",
		"SA","SB","SC","SD","SE","SG","SH","SI","SJ","SK","SL","SM","SN","SO","SR","SS","ST","SV","SX","SY","SZ",
		"TC","TD","TF","TG","TH","TJ","TK","TL","TM","TN","TO","TR","TT","TV","TW","TZ",
		"UA","UG","UM","US","UY","UZ",
		"VA","VC","VE","VG","VI","VN","VU",
		"WF","WS",
		"YE","YT",
		"ZA","ZM","ZW"
	]
}